FROM node:14-alpine
WORKDIR /usr/src/companies-service
COPY package*.json \
  .env /usr/src/companies-service/
RUN npm install --silent
COPY . /usr/src/companies-service/
EXPOSE 3000
CMD ["npm", "start"]