FROM node:14-alpine
WORKDIR /usr/src/profiles-service
COPY package*.json \
  .env /usr/src/profiles-service/
RUN npm install --silent
COPY . /usr/src/profiles-service/
EXPOSE 3002
CMD ["npm", "start"]